spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/endterm
    name: endterm
    username: admin
    password: Pass@word
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false
server: 
  error: 
    include-stacktrace: always
